apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "portal.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}   # paasxpert-k8s-portal.platform.101.55.126.222.nip.io
    http:
     paths:
     - path: /
       backend:
        serviceName: {{ include "portal.fullname" . }}-svc
        servicePort: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tls.secretName }}