apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-svc
  labels:
      app: {{ include "portal.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetport }}
  selector:
    app: {{ include "portal.fullname" . }}