{{- if .Values.rbac.create }}
{{- $serviceName := include "jenkins.fullname" . -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName}}
  labels:
    app: {{ $serviceName}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ $serviceName}}
  name: {{ $serviceName }}-schedule-agents
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - persistentvolumeclaims
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ $serviceName }}
  name: {{ $serviceName }}-schedule-agents
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceName }}-schedule-agents
subjects:
- kind: ServiceAccount
  name: {{ $serviceName }}
{{- end }}
