apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "jenkins.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "jenkins.fullname" . }}
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "jenkins.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.slavelistener.port }}
      targetPort: {{ .Values.service.slavelistener.port }}
      protocol: TCP
      name: slavelistener
  selector:
    app: {{ include "jenkins.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
